name: Build and Archive

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Bun dependencies (ratus-admin)
        run: |
          cd ratus-admin
          bun install

      - name: Install Bun dependencies (ratus-server)
        run: |
          cd ratus-server
          bun install

      - name: Build with build.bat
        shell: cmd
        run: build.bat

      - name: Archive build outputs
        uses: actions/upload-artifact@v4
        with:
          name: ratus-build-artifact
          path: |
            !ratus-production/
